# Generated by Django 4.2.16 on 2025-11-10 06:53

import apps.pqrs.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PQRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_radicado', models.CharField(default=apps.pqrs.models.generar_radicado, editable=False, max_length=20, unique=True, verbose_name='Número de Radicado')),
                ('tipo', models.CharField(choices=[('peticion', 'Petición'), ('queja', 'Queja'), ('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia')], max_length=20, verbose_name='Tipo')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_tramite', 'En Trámite'), ('vencido', 'Vencido'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_radicacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Radicación')),
                ('fecha_limite_respuesta', models.DateTimeField(verbose_name='Fecha Límite de Respuesta')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('dias_restantes', models.IntegerField(default=0, verbose_name='Días Restantes')),
                ('color_semaforo', models.CharField(choices=[('verde', 'Verde - En plazo'), ('amarillo', 'Amarillo - Próximo a vencer'), ('rojo', 'Rojo - Vencido')], default='verde', max_length=10, verbose_name='Color del Semáforo')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='pqrs_attachments/%Y/%m/', verbose_name='Archivo Adjunto')),
                ('area_responsable', models.CharField(blank=True, max_length=100, verbose_name='Área Responsable')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pqrs_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'PQRS',
                'verbose_name_plural': 'PQRS',
                'ordering': ['-fecha_radicacion'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaPQRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField(verbose_name='Respuesta')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Respuesta')),
                ('notificado', models.BooleanField(default=False, verbose_name='Notificado')),
                ('pqrs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='pqrs.pqrs', verbose_name='PQRS')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'ordering': ['-fecha_respuesta'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPQRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=20, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(max_length=20, verbose_name='Estado Nuevo')),
                ('observacion', models.TextField(verbose_name='Observación')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cambio')),
                ('pqrs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='pqrs.pqrs', verbose_name='PQRS')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial',
                'verbose_name_plural': 'Historiales',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.AddIndex(
            model_name='pqrs',
            index=models.Index(fields=['numero_radicado'], name='pqrs_pqrs_numero__1bd851_idx'),
        ),
        migrations.AddIndex(
            model_name='pqrs',
            index=models.Index(fields=['estado', 'fecha_radicacion'], name='pqrs_pqrs_estado_ae8699_idx'),
        ),
        migrations.AddIndex(
            model_name='pqrs',
            index=models.Index(fields=['color_semaforo'], name='pqrs_pqrs_color_s_7b2395_idx'),
        ),
    ]
