# Generated by Django 4.2.16 on 2025-11-11 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pqrs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pqrs_creada', 'PQRS Creada'), ('pqrs_respondida', 'PQRS Respondida'), ('pqrs_cerrada', 'PQRS Cerrada'), ('pqrs_vencida', 'PQRS Vencida')], max_length=20, verbose_name='Tipo')),
                ('destinatario_email', models.EmailField(max_length=254, verbose_name='Destinatario')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('enviado', models.BooleanField(default=False, verbose_name='Enviado')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('error', models.TextField(blank=True, verbose_name='Error')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('pqrs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='pqrs.pqrs', verbose_name='PQRS')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
